### PR TITLE
Add stringMethodOptionsExtension

### PR DESCRIPTION
**Pull request by weitzj**
This helper function can be used on service methods
to read options, which extend method options by a string.

e.g.

It is possible to read "Some string" for a custom

`my_method_option.bar` message option extension.

See:

https://developers.google.com/protocol-buffers/docs/proto#customoptions

on how to define a custom extension and referencing is by a fieldID.

```
service MyService {

  rpc MyMethod(RequestType) returns(ResponseType) {
    option (my_method_option.bar) = "Some string";
  }
}
```

If `my_method_option.bar` was defined for `fieldID: 50000`
one can reference it using protoc-gen-template like:

```
{{- stringMethodOptionsExtension 50000 .method }}
```

### CODE REVIEW

**Comment by weitzj** [comment]
@moul

**Comment by weitzj** [comment]
Hi. Is there anything I can help you with to get this merged?

**Comment by moul** [comment]
Hi @weitzj sorry for the delay and thank you for your PR :)

**Comment by weitzj** [comment]
Thank you. This is a great tool.

**Pull request merged**
