### PR TITLE
Concatenate if file already exist

### PR DESCRIPTION
**Pull request by gfanton**
For the moment, if protoc try to write on the same file it will produce an error.
This will allow to concat the file instead.

### CODE REVIEW

**Comment by gfanton** [comment]
Should i make this as an arguments?
like `concat=true`

**Comment by zoontek** [comment]
LGTM 👍

**Comment by zoontek** [comment]
As this PR break the actual library logic, it could be great if @moul check if this new comportement doesn't break anything else.

**Comment by moul** [comment]
LGTM

**Pull request merged**
