### PR TITLE
fix: error with multiple files and custom options

### LINKED ISSUE #150: Usage of custom options
I use custom options in my proto file, but can't get access to it.
How should it work?

The proto:
``` proto
syntax = "proto3";
package myservice;

import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
    string comment = 51000;
}

message Data {
    string data = 1;
}

service MyService {
    rpc DoSomething(Data) returns (Data) { 
        option (comment) = "This method does someting."; 
    }
}
```
and the template:
``` go
package {{ .File.Package }}

import (
    "context"
)

type Client interface {
    {{ range .Service.Method }}
    // {{ stringMethodOptionsExtension 51000 . }}
    {{ .Name }}(ctx context.Context, req *{{ .InputType | trimstr "." }}) (*{{ .OutputType | trimstr "." }}, error)
    {{ end }}
}
```

If I call `protoc --gotemplate_out=template_dir=.:. -I. ./my-service.proto`, I get the error:
```
panic: template: client.go.tmpl:9:10: executing "client.go.tmpl" at <stringMethodOptionsExtension 51000 .>: error calling stringMethodOptionsExtension: runtime error: slice bounds out of range [3:2]
```

If I dump the data in JSON, I can see, that the method options are empty. Is this intended?
Extract from JSON:
``` json
{
...
  "file": {
...
    "service": [
      {
        "name": "MyService",
        "method": [
          {
            "name": "DoSomething",
            "input_type": ".myservice.Data",
            "output_type": ".myservice.Data",
            "options": {}
          }
        ]
      }
    ],
    "extension": [
      {
        "name": "comment",
        "number": 51000,
        "label": 1,
        "type": 9,
        "extendee": ".google.protobuf.MethodOptions",
        "json_name": "comment"
      }
    ],
...
}
```

Thanks in advance for any hints.

### PR DESCRIPTION
**Pull request by Mik-**
This pull request fixes #150.
I also fixed concurrent map read/write errors, when processing multiple template files.

### CODE REVIEW

**Comment by Mik-** [comment]
@moul do I have to do something further here?
Unfortunately I can't remove the WIP label and I think, the linter warnings about deprecated dependencies should be solved in another pull request as it could be a breaking change.

**Comment by moul** [comment]
Hey @Mik- :wave:, thank you for this PR, and sorry, I didn't open the details of the golangci-lint issue, I though it was something added by you, I'll make a full review later today

**Comment by Darko-Huma** [comment]
@moul @Mik- there's some deprecated methods from protobuf on added lines we should change them
```SA1019: proto.RegisteredExtensions is deprecated: Use protoregistry.GlobalTypes.RangeExtensionsByMessage instead.  (staticcheck)```

**Comment by Dzalevski** [comment]
@moul @Mik- there's some deprecated methods from protobuf on added lines we should change them
```SA1019: proto.RegisteredExtensions is deprecated: Use protoregistry.GlobalTypes.RangeExtensionsByMessage instead.  (staticcheck)```

**Comment by Dzalevski** [comment]
@Mik- now it's great thank you! :) 
Just change the imports they are also depr

**Comment by Mik-** [comment]
_Just_ changing the imports is not that easy. The Plugin-API has changed, too. So it would be a bigger rework.

**Comment by moul** [comment]
Thank you! And sorry for the delay :)

**Pull request merged**
